# Generated by Django 4.2.17 on 2026-06-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reputationscore',
            name='overall_score',
            field=models.IntegerField(default=0),
        ),
    ]
