# Generated by Django 4.2.17 on 2026-06-02 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reputation', '0002_reputationscore_overall_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='reputationscore',
            name='deployment_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='rank_tier',
            field=models.CharField(default='Bronze', max_length=20),
        ),
        migrations.CreateModel(
            name='MonthlyRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
