# Generated by Django 4.2.17 on 2026-06-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0003_reputationscore_deployment_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reputationscore',
            name='reviews_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='tasks_completed',
            field=models.IntegerField(default=0),
        ),
    ]
