# Generated by Django 4.2.17 on 2026-06-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0004_reputationscore_reviews_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyranking',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyranking',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlyranking',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlyranking',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
