# Generated by Django 4.2.17 on 2026-06-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0006_alter_review_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyranking',
            options={'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='applications_accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='sprint_completion_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyranking',
            name='month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyranking',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyranking',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
