# Generated by Django 4.2.17 on 2026-06-18 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='content',
            new_name='generated_resume',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='Untitled Resume', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
