# Generated by Django 4.2.17 on 2026-06-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_rename_content_resume_generated_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
