# Generated by Django 4.2.17 on 2026-07-02 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0004_auto_20260703_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='legal/vendors/')),
                ('active', models.BooleanField(default=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startupprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trademark_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Objection', 'Objection'), ('Registered', 'Registered')], max_length=20)),
                ('application_number', models.CharField(max_length=100)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startupprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ShareholderAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='legal/shareholders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startupprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='legal/nda/')),
                ('signed', models.BooleanField(default=False)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startupprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IPAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='legal/ip/')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startupprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FounderAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='legal/founders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startupprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('contract_file', models.FileField(upload_to='legal/employees/')),
                ('active', models.BooleanField(default=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startupprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClientAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('file', models.FileField(upload_to='legal/clients/')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startupprofile')),
            ],
        ),
    ]
