# Generated by Django 4.2.17 on 2026-07-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_startupapplication'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='startups.startupprofile'),
        ),
    ]
