# Generated by Django 4.2.17 on 2026-06-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0003_alter_activity_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
