# Generated by Django 4.2.17 on 2026-07-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0005_sprintproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
