# Generated by Django 4.2.17 on 2026-06-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementjob',
            name='experience_required',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
