# Generated by Django 4.2.17 on 2026-07-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_placementjob_experience_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementjob',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
