# Generated by Django 4.2.17 on 2026-06-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupprofile',
            name='team_size',
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
