# Generated by Django 4.2.17 on 2026-07-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_alter_startupprofile_options_startupprofile_address_and_more'),
    ]

    operations = [
    ]
