# Generated by Django 4.2.17 on 2026-06-16 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursemodule_skill_tags'),
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
