# Generated by Django 4.2.17 on 2026-06-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('startup', 'Startup'), ('talent', 'Talent')], max_length=20, null=True),
        ),
    ]
