"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--cd4@!-=yy9dk+d48q^pa3rhv#y(lw5^*!etrf-j&&+$t6=)t7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = [
    "c942-117-213-115-145.ngrok-free.app",
    "127.0.0.1",
    "*",   # Remove in production
]

CSRF_TRUSTED_ORIGINS = [
    "https://c942-117-213-115-145.ngrok-free.app",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
    'sprints',
    'accounts',
    'dashboard',
    'reputation',
    'startups',
    'talents',
    'notifications',
    'activities',
    'courses',
    'webinars',
    'projects',
    'internships',
    'placements',
    'mentors',
    'certificates',
    'payments',
    'ai_engine',
    'interviews',
    'offers',
    'adminpanal',
    'calendar_app',
    'people',
    'finance',
    'compliance',
    'legal',
    'crm',
    'operations',
    'analytics',
    'execution',
    'sales',
    'banking',
    'intelligence',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.RoleBasedRedirectMiddleware',
]

ROOT_URLCONF = 'core.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.startup_context',
                'core.context_processors.user_roles',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'


STATICFILES_DIRS = [
    BASE_DIR / 'static'
]


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'accounts.User'



RAZORPAY_KEY_ID = "rzp_test_T3gQAQZw24uRli"

RAZORPAY_KEY_SECRET = "NQgWOXfD7e5XckVM3ViNbRap"




# core/settings.py

# ============================================
# EMAIL CONFIGURATION
# ============================================

# Email Backend
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SMTP Configuration (Using Gmail)
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# Email Credentials
EMAIL_HOST_USER = 'shajaygopi2001@gmail.com'
EMAIL_HOST_PASSWORD = 'aves xenb ncco vcqw'  # App password

# ============================================
# EMAIL SETTINGS
# ============================================

# Default From Email
DEFAULT_FROM_EMAIL = f'PANZIA <{EMAIL_HOST_USER}>'
SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_SUBJECT_PREFIX = '[PANZIA] '

# ============================================
# SITE URL (for email links)
# ============================================

# For local development
SITE_URL = 'http://127.0.0.1:8000'

# For production with ngrok (uncomment when using ngrok)
# SITE_URL = 'https://c942-117-213-115-145.ngrok-free.app'

# For production with custom domain
# SITE_URL = 'https://yourdomain.com'

# ============================================
# FOR DEVELOPMENT - Console Email Backend
# ============================================
# Uncomment the line below to see emails in console instead of sending
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'