# Generated by Django 4.2.17 on 2026-06-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='skill_tags',
            field=models.CharField(blank=True, help_text='python,django,ai,react', max_length=300),
        ),
    ]
