# Generated by Django 4.2.17 on 2026-06-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0002_alter_sprint_startup_alter_sprintapplication_talent_and_more'),
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='talentprofile',
            name='experience_level',
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='talents/'),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='talentprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='sprints.skill'),
        ),
    ]
