# Generated by Django 4.2.17 on 2026-06-18 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talents', '0003_portfolioproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioproject',
            name='featured',
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='project_type',
            field=models.CharField(choices=[('Sprint', 'Sprint'), ('Personal', 'Personal'), ('Freelance', 'Freelance'), ('Startup', 'Startup'), ('OpenSource', 'Open Source')], default='Personal', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='skills',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
