# Generated by Django 4.2.17 on 2026-06-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0004_remove_portfolioproject_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='sprint_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Sprint', 'Sprint'), ('Personal', 'Personal'), ('Freelance', 'Freelance'), ('Startup', 'Startup'), ('OpenSource', 'Open Source')], max_length=20, null=True),
        ),
    ]
