# Generated by Django 4.2.17 on 2026-06-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0005_sprintproject'),
        ('talents', '0005_portfolioproject_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioproject',
            name='skills',
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='skills',
            field=models.ManyToManyField(blank=True, to='sprints.skill'),
        ),
    ]
