# Generated by Django 4.2.17 on 2026-06-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0007_remove_portfolioproject_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
