# Generated by Django 4.2.17 on 2026-06-27 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_remove_startupprofile_team_size_and_more'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='startups.startupprofile'),
        ),
    ]
