# Generated by Django 4.2.17 on 2026-06-27 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_remove_startupprofile_team_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0002_department_startup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__first_name']},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_source',
            field=models.CharField(choices=[('Talent Pool', 'Talent Pool'), ('Manual', 'Manual'), ('Transfer', 'Transfer')], default='Talent Pool', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_payroll_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Onboarding', 'Onboarding'), ('Active', 'Active'), ('Probation', 'Probation'), ('Notice Period', 'Notice Period'), ('Exited', 'Exited')], default='Onboarding', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_mode',
            field=models.CharField(choices=[('Office', 'Office'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='Office', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='startups.startupprofile'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Intern', 'Intern'), ('Contract', 'Contract'), ('Freelancer', 'Freelancer')], default='Full Time', max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='people.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='startups.startupprofile'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('startup', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('startup', 'employee_id')},
        ),
    ]
