# Generated by Django 4.2.17 on 2026-06-30 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_payroll_options_payroll_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payslip', 'verbose_name_plural': 'Payslips'},
        ),
        migrations.AddField(
            model_name='payslip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='payroll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='people.payroll'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pdf',
            field=models.FileField(help_text='Upload PDF file of the payslip', upload_to='payslips/'),
        ),
    ]
