# Generated by Django 4.2.17 on 2026-06-30 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_payslip_options_payslip_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Payslip', 'verbose_name_plural': 'Payslips'},
        ),
        migrations.AddField(
            model_name='payslip',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='html_content',
            field=models.TextField(blank=True, help_text='HTML content for the payslip', null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='is_generated',
            field=models.BooleanField(default=False, help_text='Whether the payslip has been generated'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the payslip record was created'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pdf',
            field=models.FileField(blank=True, help_text='Generated PDF file', null=True, upload_to='payslips/'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the payslip was last updated'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['generated_at'], name='people_pays_generat_c2a7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['is_generated'], name='people_pays_is_gene_f581cc_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['payroll'], name='people_pays_payroll_b02f67_idx'),
        ),
    ]
