# Generated by Django 4.2.17 on 2026-06-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_alter_payslip_options_payslip_generated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['date'], 'verbose_name': 'Holiday', 'verbose_name_plural': 'Holidays'},
        ),
        migrations.AddField(
            model_name='holiday',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about the holiday', null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_company_holiday',
            field=models.BooleanField(default=True, help_text='Whether this is a company-wide holiday'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(help_text='Date of the holiday'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('National', '🇮🇳 National Holiday'), ('Public', '🏛️ Public Holiday'), ('Company', '🏢 Company Holiday'), ('Festival', '🎉 Festival'), ('Optional', '📅 Optional Holiday')], default='National', max_length=100),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(help_text='Name of the holiday', max_length=200),
        ),
    ]
