# Generated by Django 4.2.17 on 2026-06-30 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0008_holiday_created_at_holiday_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resignation_date', models.DateField(help_text='Date when resignation was submitted')),
                ('last_working_day', models.DateField(help_text='Last working day of the employee')),
                ('reason', models.CharField(choices=[('better_opportunity', 'Better Opportunity'), ('career_growth', 'Career Growth'), ('salary', 'Salary/Package'), ('relocation', 'Relocation'), ('personal', 'Personal Reasons'), ('health', 'Health Issues'), ('retirement', 'Retirement'), ('other', 'Other')], default='other', max_length=50)),
                ('reason_description', models.TextField(blank=True, help_text='Detailed reason for exit', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('exit_interview_date', models.DateField(blank=True, help_text='Date of exit interview', null=True)),
                ('exit_interview_notes', models.TextField(blank=True, help_text='Notes from exit interview', null=True)),
                ('is_eligible_for_rehire', models.BooleanField(default=True, help_text='Whether the employee is eligible for rehire')),
                ('feedback', models.TextField(blank=True, help_text='Employee feedback during exit', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exits', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_requests', to='people.employee')),
            ],
            options={
                'verbose_name': 'Exit Request',
                'verbose_name_plural': 'Exit Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
