# Generated by Django 4.2.17 on 2026-06-30 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0009_exitrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancereview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Performance Review', 'verbose_name_plural': 'Performance Reviews'},
        ),
        migrations.AddField(
            model_name='performancereview',
            name='areas_for_improvement',
            field=models.TextField(blank=True, help_text='Areas where the employee can improve', null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='goals',
            field=models.TextField(blank=True, help_text='Goals for the next review period', null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='review_period',
            field=models.CharField(choices=[('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('annual', 'Annual'), ('project_based', 'Project Based')], default='quarterly', max_length=50),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='strengths',
            field=models.TextField(blank=True, help_text='Key strengths of the employee', null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='people.employee'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐ 1 - Poor'), (2, '⭐⭐ 2 - Below Average'), (3, '⭐⭐⭐ 3 - Average'), (4, '⭐⭐⭐⭐ 4 - Good'), (5, '⭐⭐⭐⭐⭐ 5 - Excellent')]),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='review',
            field=models.TextField(help_text='Detailed performance review'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_performances', to=settings.AUTH_USER_MODEL),
        ),
    ]
