# Generated by Django 4.2.17 on 2026-07-02 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_alter_performancereview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='default_check_in',
            field=models.TimeField(blank=True, help_text='Default check-in time', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='default_check_out',
            field=models.TimeField(blank=True, help_text='Default check-out time', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_day_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Hours for full day', max_digits=4),
        ),
        migrations.AddField(
            model_name='employee',
            name='grace_period_minutes',
            field=models.IntegerField(default=15, help_text='Grace period in minutes'),
        ),
        migrations.AddField(
            model_name='employee',
            name='half_day_hours',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='Hours for half day', max_digits=4),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Overtime rate multiplier', max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning Shift (9:30 AM - 6:30 PM)'), ('evening', 'Evening Shift (2:00 PM - 11:00 PM)'), ('night', 'Night Shift (10:00 PM - 7:00 AM)'), ('flexible', 'Flexible Hours'), ('remote', 'Remote Work')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_end_time',
            field=models.TimeField(blank=True, help_text='Work end time', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_start_time',
            field=models.TimeField(blank=True, help_text='Work start time', null=True),
        ),
        migrations.CreateModel(
            name='DepartmentTimingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_time', models.TimeField(default='09:30')),
                ('work_end_time', models.TimeField(default='18:30')),
                ('grace_period_minutes', models.IntegerField(default=15)),
                ('half_day_hours', models.DecimalField(decimal_places=2, default=4.0, max_digits=4)),
                ('full_day_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('shift', models.CharField(blank=True, choices=[('morning', 'Morning Shift (9:30 AM - 6:30 PM)'), ('evening', 'Evening Shift (2:00 PM - 11:00 PM)'), ('night', 'Night Shift (10:00 PM - 7:00 AM)'), ('flexible', 'Flexible Hours'), ('remote', 'Remote Work')], max_length=50, null=True)),
                ('weekly_off_days', models.JSONField(blank=True, default=list, help_text='List of weekly off days (0=Monday, 6=Sunday)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timing_config', to='people.department')),
            ],
        ),
    ]
