# Generated by Django 4.2.17 on 2026-07-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_employee_default_check_in_employee_default_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='location_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/'),
        ),
    ]
