# Generated by Django 4.2.17 on 2026-07-02 23:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_attendance_check_in_status_attendance_device_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-check_in'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='grace_period_minutes',
            field=models.IntegerField(default=15, help_text='Grace period in minutes'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_overtime',
            field=models.BooleanField(default=False, help_text='Whether this attendance has overtime'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours worked', max_digits=4),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_end_time',
            field=models.TimeField(blank=True, help_text='Work end time for this specific attendance', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_start_time',
            field=models.TimeField(blank=True, help_text='Work start time for this specific attendance', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_status',
            field=models.CharField(blank=True, choices=[('early', 'Early'), ('on_time', 'On Time'), ('slightly_late', 'Slightly Late'), ('late', 'Late'), ('very_late', 'Very Late')], help_text='Status based on check-in time (Early, On Time, Late, etc.)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='device_info',
            field=models.CharField(blank=True, help_text='Device used to mark attendance', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='people.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the device', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='location_address',
            field=models.TextField(blank=True, help_text='Address of attendance location', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of attendance location', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of attendance location', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='photo',
            field=models.ImageField(blank=True, help_text='Attendance verification photo', null=True, upload_to='attendance_photos/'),
        ),
    ]
