# Generated by Django 4.2.17 on 2026-07-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('annual', 'Annual Leave'), ('earned', 'Earned Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('bereavement', 'Bereavement Leave'), ('study', 'Study Leave'), ('other', 'Other')], default='casual', max_length=100),
        ),
    ]
