# Generated by Django 4.2.17 on 2026-07-06 19:44

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='photo',
            field=models.ImageField(blank=True, help_text='Attendance verification photo', null=True, upload_to=people.models.get_attendance_photo_path),
        ),
    ]
