# Generated by Django 4.2.17 on 2026-07-06 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_auto_20260703_0207'),
        ('people', '0015_alter_attendance_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='startup',
            field=models.ForeignKey(blank=True, help_text='Startup this holiday belongs to (leave blank for system-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='startups.startupprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('startup', 'date', 'name')},
        ),
    ]
