# Generated by Django 4.2.17 on 2026-07-14 15:06

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_holiday_startup_alter_holiday_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checkin_photo',
            field=models.ImageField(blank=True, help_text='Check-in verification photo', null=True, upload_to=people.models.get_attendance_photo_path),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkout_photo',
            field=models.ImageField(blank=True, help_text='Check-out verification photo', null=True, upload_to=people.models.get_attendance_photo_path),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='photo',
            field=models.ImageField(blank=True, help_text='Attendance verification photo (deprecated)', null=True, upload_to=people.models.get_attendance_photo_path),
        ),
    ]
